### ISSUE TITLE
tempfile.mkdtemp sometimes fails under fso?

### ISSUE THREAD

**Issue by tedbrandston** [metagriffin/fso#1]
I'm not 100% convinced that this is an issue with fso, but it looks like a call to `tempfile.mkdtemp` will fail if the fso is active _and_ `tempfile.mkdtemp` hasn't been called.

simplest repro for me:
```
[ted@localhost]$ venv/bin/python
>>> import tempfile, fso
>>> fso.push()
<fso.filesystemoverlay.FileSystemOverlay object at 0x7f7279b26490>
>>> tempfile.mkdtemp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/tempfile.py", line 331, in mkdtemp
    dir = gettempdir()
  File "/usr/lib64/python2.7/tempfile.py", line 275, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib64/python2.7/tempfile.py", line 200, in _get_default_tempdir
    with _io.open(fd, 'wb', closefd=False) as fp:
TypeError: coercing to Unicode: need string or buffer, int found
```
And all subsequent calls while the fso remains active will fail.

But when I went to confirm that mkdtemp was working at all I found this:
```
[ted@localhost]$ venv/bin/python
>>> import tempfile, fso
>>> tempfile.mkdtemp()
'/tmp/tmpPPE6VM'
>>> fso.push()
<fso.filesystemoverlay.FileSystemOverlay object at 0x7f219ac07490>
>>> tempfile.mkdtemp()
'/tmp/tmpWrHhoT'
```

I can even `fso.push()`, see it fail, `fso.pop()`, see it succeed, `fso.push()`, see it continue succeeding.

Started to look at the tempfile code to see if I could track this down, but don't have the time at this moment, and have a workaround ^.

Even a confirmation that this couldn't possibly be fso's fault would be helpful. Thanks!

**Comment by metagriffin** [comment]
i was not aware of this issue -- thanks for bringing it to my attention.
i'll take a look, but can you tell me exactly which version of python 2.7 you are using?

**Comment by tedbrandston** [comment]
```
[ted@localhost]$ venv/bin/python
Python 2.7.12 (default, Sep 29 2016, 12:52:02) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux2
```
